### ISSUE TITLE
Plugin.new fails when reading from local file

### ISSUE THREAD

**Issue by ndrean** [extism/elixir-sdk#17]
Firstly, thanks for this work! I run the example  in an `iex` session with URL, works fine.

Then I made a trial reading a local wasm file instead as I don't want to serve this file. This file  works, tested with `wasmex`.

```elixir
Mix.install([:wasmex])

bin = File.read!("my-app.wasm")
{:ok, pid} = Wasmex.start_link(%{binary: bin})
{:ok, res} = Wasmex.call_function(pid, "add", [1,2])
res

# 3 <- :ok
```

If I refer to the [manifest documentation](https://extism.org/docs/concepts/manifest/), I should be able to use it like this: 

```elixir
Mix.install([:extism])

wasm = File.read!("my-app.wasm")
hash = :crypto.hash(:sha256, wasm) |> Base.encode16() |> String.downcase()
manifest = %{wasm: [%{data: wasm, hash: hash}]}

Extism.Plugin.new(manifest, false)
```
However, the "manifest" is parsed into json. This fails (I tried `Jason` and `JSON`) because of the wasm binary:
<https://github.com/extism/elixir-sdk/blob/79d20e1b3778e0c7544902ee53a3e5dfe8a43b0f/lib/extism/plugin.ex#L29>

My error is as below. So my question: how do you this work?

<details><summary>Error</summary>

```elixir
(FunctionClauseError) no function clause matching in JSON.Encoder.BitString.encode_binary_recursive/2

    The following arguments were given to JSON.Encoder.BitString.encode_binary_recursive/2:

        # 1
        <<128, 128, 192, 0, 11, 7, 16, 2, 6, 109, 101, 109, 111, 114, 121, 2, 0, 3, 97,
          100, 100, 0, 0, 10, 214, 1, 2, 157, 1, 1, 16, 127, 35, 128, 128, 128, 128, 0,
          33, 2, 65, 16, 33, 3, 32, 2, 32, 3, 107, 33, ...>>

        # 2
        [65, ~c"1000", 117, 92, 127, ~c"1000", 117, 92, 116, 92, ~c"6000", 117, 92,
         ~c"1100", 117, 92, ~c"0000", 117, 92, ~c"1000", 117, 92, ~c"3000", 117, 92,
         ~c"5000", 117, 92, ~c"1000", 117, 92, ~c"0000", 117, 92, ~c"2000", 117, 92,
         ~c"3000", 117, 92, ~c"3000", 117, 92, ~c"0000", 117, 92, 127, 127, 127, 127,
         ...]

    Attempted function clauses (showing 2 out of 2):

        defp encode_binary_recursive(<<head::utf8, tail::binary>>, acc)
        defp encode_binary_recursive(<<>>, acc)

    (json 1.4.1) lib/json/encoder/default_implementations.ex:92: JSON.Encoder.BitString.encode_binary_recursive/2
    (json 1.4.1) lib/json/encoder/default_implementations.ex:90: JSON.Encoder.BitString.encode/1
    (json 1.4.1) lib/json/encoder/helpers.ex:28: JSON.Encoder.Helpers.encode_item/1
    (json 1.4.1) lib/json/encoder/helpers.ex:23: anonymous fn/1 in JSON.Encoder.Helpers.dict_encode/1
    (elixir 1.17.3) lib/enum.ex:1804: anonymous fn/2 in Enum.map_join/3
    (elixir 1.17.3) lib/enum.ex:1773: anonymous fn/4 in Enum.map_intersperse/3
    (stdlib 6.1.2) maps.erl:860: :maps.fold_1/4
    iex:4: (file)
```
</details>

**Comment by bhelx** [comment]
Could you try the `path` variant? it will be more performant to let the runtime read and load from disk instead of you doing it and copying it over. should look something like:

```elixir
manifest = %{wasm: [%{path: "my-app.wasm"}]}
```

path may need to be absolute. i'm not sure.

**Comment by ndrean** [comment]
ok! relative seems to work with "path". However, how to pass several arguments?

```elixir
{:ok, plugin} = Extsim.Plugin.new(manifest, false)

Extism.Native.plugin_has_function(plugin.plugin, "add")

# => true

# I have 2 arguments and it expects a string...I tried variations "1,2"...
Extism.Plugin.call(plugin, "add", "[1, 2]")

# {:error, "expected 2 arguments, got 0"}
```

The function exposed as WebAssembly comes from Zig code below compiled to WASM. Nothing huge...

```zig
export fn add(a: i32, b: i32) i32 {
   return a+b;
}
```

**Comment by bhelx** [comment]
wasmex and extism are two different things. wasmex is a wrapper around wasmtime and thus the interface is for working with raw wasm. extism is runtime agnostic, and we don't typically expose a raw wasm interface to the user, though there are ways to access it. if you want to call some rust code you should write an extism plugin using the rust-pdk: https://github.com/extism/rust-pdk

edit: oh, i see this is zig code. we do support zig though: https://github.com/extism/zig-pdk

**Comment by ndrean** [comment]
Yes, I saw but I compiled the Zig code into WASM, and I am just calling the WASM. I just showed what the WASM exposes. Extism sees the function as I put the test Native.plugin_has_function.
Now my question is just: how to you pass several arguments?

**Comment by bhelx** [comment]
sorry if i'm sounding cryptic, just trying to explain how it works beyond just this example.

>  Now my question is just: how to you pass several arguments?

you can't pass any arguments. extism exports have a convention of `input` and `output` through a shared buffer. you don't control the wasm arguments or the return value. 

in your scenario, if you want to make an `add` function that accepts two numbers, you need to turn those arguments into an input. we often suggest people use some kind of well known serialization / deserialization format. but since it's just a byte buffer you could also just pack and unpack the bytes directly.

**Comment by ndrean** [comment]
ah ok, I can't just run random wasm code. I need to build it for Extism. It's indeed another story. So I close this, but you should perhaps put a warning on this.
Thks
